version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./courses:/home/app/autolab/courses
      - ./db:/home/app/autolab/db
    depends_on:
      - "tango"
  tango:
    image: autolabproject/tango-dev:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "redis"
  redis:
    image: 'redis:latest'

